### ISSUE TITLE
Problems installing m2e-code-quality with (specifically) the Checkstyle Eclipse plugin on Eclipse Mars.1 Release (4.5.1)

### ISSUE THREAD

**Issue by anton-johansson** [m2e-code-quality/m2e-code-quality#82] opened 2016-02-22 07:18 UTC
OS: Ubuntu 15.10 (Wily Werewolf)
Eclipse Version: Mars.1 Release (4.5.1)

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Checkstyle configuration plugin for M2Eclipse 1.0.0.201408150901 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201408150901)
  Missing requirement: Checkstyle configuration plugin for M2Eclipse 1.0.0.201408150901 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201408150901) requires 'net.sf.eclipsecs.core [5.2.0,6.0.0)' but it could not be found
```

**Comment by ArloL** [comment] 2016-02-22 10:12
Hi @anton-johansson, thanks for reporting the issue.

Can you reproduce this problem with a fresh Eclipse installation?
If yes, can you please describe your exact steps so that I can try reproducing the issue?

What your error message tells me is that you are trying to install an old version of the plugin. The latest release should start with 1.0.0.2016 not 1.0.0.**2014**

Did you manually add the update site or are you using the m2e catalog? If you added the update site yourself make sure to use http://m2e-code-quality.github.io/m2e-code-quality/site/latest/

**Comment by anton-johansson** [comment] 2016-02-22 10:47
Hi @ArloL.

I will try in a fresh installation as soon as I have time, and see if I can get you a proper step-by-step guide to reproduce it.

Hmm, allright. Strange. When opening the marketplace in Eclipse, I couldn't find m2e-code-quality. Instead, I went [here](https://marketplace.eclipse.org/content/m2e-code-quality) and dragged the <kbd>Install</kbd> button to my Eclipse workspace.

I'll try using the <kbd>Install new software...</kbd> using the link you provided, and get back to you.

Thanks!

**Comment by anton-johansson** [comment] 2016-02-22 11:03
Yeah, that worked like a charm. My bad, sorry for that.

Thanks a bunch!

**Comment by ArloL** [comment] 2016-02-22 15:30
Thanks for posting that link. They have the wrong update site. I'll try changing it.

**Comment by rgentz** [comment] 2017-01-30 19:41
Hi @ArloL 

I have the same problem that I cannot install the software using the "Install new Software..." button.
Both http://m2e-code-quality.github.io/m2e-code-quality/site/latest/ and http://m2e-code-quality.github.io/m2e-code-quality/site/develop/


Each time I get the error: 
Cannot complete the install because one or more required items could not be found.
  Software being installed: Checkstyle configuration plugin for M2Eclipse 1.0.0.201605301854 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201605301854)
  Missing requirement: Checkstyle configuration plugin for M2Eclipse 1.0.0.201605301854 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201605301854) requires 'net.sf.eclipsecs.core 5.2.0' but it could not be found

How can I get it installed? I tried both Luna and Mars installations of Eclipse and both give the same error....
Thanks a lot!

**Comment by ArunKumarGK** [comment] 2017-02-08 23:13
Even I am facing the same issue. I am trying to install m2e-checkstyle / m2e-pmd with Eclipse Neon. This is a fresh installation. Below is the error I am getting :

Missing requirement: Checkstyle configuration plugin for M2Eclipse 1.0.0.201608091842 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201608091842) requires 'net.sf.eclipsecs.core 5.2.0' but it could not be found

**Comment by ArloL** [comment] 2017-02-20 20:56
Could you perhaps post a longer stacktrace?

I believe it might be this error: http://stackoverflow.com/questions/42128981/eclipse-pmd-plug-in-handshake-failure

**Comment by rythompson** [comment] 2017-02-27 17:12
That is the entire stacktrace given by eclipse. I am seeing the same error on a fresh install of Eclipse Neon. I tried replacing the security jars with the ones found at:
 http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
but I still received the same error.

**Comment by ArloL** [comment] 2017-02-28 18:33
Hi @rythompson, could it be that you forgot to attach the stacktrace?

**Comment by rythompson** [comment] 2017-02-28 18:47
Sorry I was referring to the stack trace in @ArunKumarGK comment. I saw the exact same thing, but that is all the information it gave. I also noticed that my java install was out of date, but updating it to 8.121 still did not help.

**Comment by RohitJ23** [comment] 2017-02-28 19:46
I'm facing the same issue on OS X on fresh Mars installation.

Cannot complete the install because one or more required items could not be found.
  Software being installed: Checkstyle configuration plugin for M2Eclipse 1.0.0.201408150901 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201408150901)
  Missing requirement: Checkstyle configuration plugin for M2Eclipse 1.0.0.201408150901 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201408150901) requires 'net.sf.eclipsecs.core [5.2.0,6.0.0)' but it could not be found

**Comment by RohitJ23** [comment] 2017-02-28 19:51
Trying the link @ArloL posted above didn't resolve it for me.

Cannot complete the install because one or more required items could not be found.
  Software being installed: Checkstyle configuration plugin for M2Eclipse 1.0.0.201608091842 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201608091842)
  Missing requirement: Checkstyle configuration plugin for M2Eclipse 1.0.0.201608091842 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201608091842) requires 'net.sf.eclipsecs.core 5.2.0' but it could not be found

**Comment by cornzy** [comment] 2017-03-06 16:36
@ArloL I just tried to install the latest version in a fresh eclipse neon and had the similar problem. I have a linux environment, my colleague using windows didn't have any problems.  

Using: http://m2e-code-quality.github.com/m2e-code-quality/site/latest
install checkstyle extension. Eclipse need very long time to find 15 solutions and finally found nothing but not to install the needed plugin. The originla problem detail:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Checkstyle configuration plugin for M2Eclipse 1.0.0.201608091842 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201608091842)
  Missing requirement: Checkstyle configuration plugin for M2Eclipse 1.0.0.201608091842 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201608091842) requires 'net.sf.eclipsecs.core 5.2.0' but it could not be found

**Comment by ArloL** [comment] 2017-03-06 19:00
Hi @cornzy,

thanks for commenting. Could you maybe look for a stack trace in the Eclipse error logs? Are you able to install only the checkstyle plugin?

**Comment by cornzy** [comment] 2017-03-08 09:15
Hi @ArloL, your are right the problem seems to be with the checkstyle plugin. In errorlog I found a  SSLHandshakeException (stacktrace below). Seems like I have to search for a solution to install checkstyle than I'll come back again :)

```
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.SNIAwareHttpClient$1.connectSocket(SNIAwareHttpClient.java:63)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:263)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by ArloL** [comment] 2017-03-08 09:42
Hi @cornzy,

thanks for trying a different approach. That error message is exactly the same as for the pmd plugin: http://stackoverflow.com/questions/42128981/eclipse-pmd-plug-in-handshake-failure

The issue is that the JVM by default only supports a limited set of ciphers and that sourceforge started using - by default unsupported - ciphers for their https traffic. The workaround is to install the Java Cryptography Extension (JCE).

Sadly there is not much else I can do other than contact the providers of the update sites to change it to a different host (e.g. GitHub Pages).

If there are other issues I will try to help of course.

**Comment by cornzy** [comment] 2017-03-08 11:39
Hi @ArloL, thank you very much - it works for me.

**Comment by ArloL** [comment] 2017-03-08 12:17
Great! Thanks for letting us know.

**Comment by stephenbanghart** [comment] 2017-03-09 21:48
Installing the JCE has fixed the issue for me as well. (Eclipse Neon 2/3)

**Comment by ArloL** [comment] 2017-03-10 06:48
Thanks for the feedback, @stephenbanghart.

**Comment by jmini** [comment] 2018-02-14 09:45
I had the same problem when is wanted to install [Checkstyle configuration plugin for M2Eclipse](https://marketplace.eclipse.org/content/m2e-code-quality) in my Eclipse Installation with Oomph.

Stacktrace:

```
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:729)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3324)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4494)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4488)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4486)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3258)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3233)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3133)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1518600206290
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Checkstyle configuration plugin for M2Eclipse 1.0.0.201705301746 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201705301746) requires 'net.sf.eclipsecs.core 5.2.0' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1518600206290
    ERROR: org.eclipse.equinox.p2.director code=0 To: com.basistech.m2e.code.quality.checkstyle.feature.feature.group 0.0.0
```

In my opinion the error occurs when the [checkstyle plugin](https://marketplace.eclipse.org/content/checkstyle-plug) is not installed in the IDE. It needs to be installed first.

Or you can tell Oomph where to get it. The update site for the Checkstyle Plugin is: `http://eclipse-cs.sourceforge.net/update/`.
My setup File now looks like this:
<img width="397" alt="Oomph setup file" src="https://user-images.githubusercontent.com/1222165/36197386-e0a90480-1173-11e8-8743-1a4c2dd9612b.png">

Source:
```
<?xml version="1.0" encoding="UTF-8"?>
<setup.p2:P2Task
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:setup.p2="http://www.eclipse.org/oomph/setup/p2/1.0">
  <requirement
      name="com.basistech.m2e.code.quality.checkstyle.feature.feature.group"/>
  <repository
      url="http://m2e-code-quality.github.io/m2e-code-quality/site/latest/"/>
  <repository
      url="http://eclipse-cs.sourceforge.net/update/"/>
</setup.p2:P2Task>

```

**Comment by vorburger** [comment] 2018-09-19 11:37
Could you please re-test with our brand new update site at https://m2e-code-quality.github.io/m2e-code-quality-p2-site/ (see #123 for #124 for background), and shout if the issue shown above, which seems to be specific to some Checkstyle Eclipse plugin-in version issue, and is not the same as the general problem with Photon (#120) reported by others? (Let's close this issue in 1 month from today if no further updates; hope that's fair.)

And yes, the Checkstyle Eclipse plugin is obviously a pre-requisite to installing this plugin.

**Comment by vorburger** [comment] 2018-09-20 14:55
@jmini thanks for feedback; let me close this issue then (we can re-open if others still hit this).

**Closed by vorburger** 2018-09-20 14:55 UTC

**Comment by t-rufang** [comment] 2021-05-31 11:22
I meet the same error in Eclipse 2021-03 JavaEE version.
Finally, I solved this problem by [Installing Eclipse Checkstyle Plugin](https://checkstyle.org/eclipse-cs/#!/install) before installing `m2e-code-quality` related plugin.

**Comment by sgesin** [comment] 2021-08-10 23:31
For some reason I was missing the [PMD Eclipse Plugin](https://github.com/pmd/pmd-eclipse-plugin) as well from the update site https://pmd.github.io/pmd-eclipse-plugin-p2-site/. After installing both the Eclipse Checkstyle Plugin mentioned in the comment above and the PMD Eclipse Plugin I was able to install m2e-code-quality.
