### ISSUE TITLE
java.lang.NoClassDefFoundError with STS 3.7.0 during maven project update

### ISSUE THREAD

**Issue by tyas1** [m2e-code-quality/m2e-code-quality#75] opened 2015-08-13 02:08 UTC
I am using Spring Tool Suite 3.7.0(STS 3.7.0) and tried to update maven project, I got following error.

>  'Updating Maven Project' has encountered a problem.
>  An internal error occurred during: "Updating Maven Project".
>
>  An internal error occurred during: "Updating Maven Project".
>   org/apache/commons/lang/StringEscapeUtils

and here is stack trace in eclipse log file.

> !MESSAGE An internal error occurred during: "Updating Maven Dependencies".
> !STACK 0
> java.lang.NoClassDefFoundError: org/apache/commons/lang/StringEscapeUtils
> 	at com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.updatePropertiesWithPropertyExpansion(MavenPluginConfigurationTranslator.java:632)
> 	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.buildCheckstyleConfiguration(EclipseCheckstyleProjectConfigurator.java:153)
> 	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.handleProjectConfigurationChange(EclipseCheckstyleProjectConfigurator.java:106)
> 	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:127)
> 	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:1000)
> 	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:783)
> 	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:919)
> 	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob$1.call(ProjectRegistryRefreshJob.java:98)
> 	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob$1.call(ProjectRegistryRefreshJob.java:1)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
> 	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
> 	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob.run(ProjectRegistryRefreshJob.java:81)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by mcampbell-src** [comment] 2015-08-20 15:44
We're seeing this error with the latest connector in a fresh Eclipse Luna install, so I don't think this is specific to Sprint Tool Suite.  I'm not seeing this issue with the following version of the connector though that I had installed a while ago in another eclipse:

Checkstyle configuration plugin for M2Eclipse	1.0.0.201503101518
Eclipse Checkstyle Plug-in 6.5.0.201504121610

**Comment by tyas1** [comment] 2015-08-21 09:00
Please try following pom.xml file.

1. create maven project in STS 3.7.0
2. confirm check style activated.
3. update maven project. You will see following exception.

  An internal error occurred during: "Updating Maven Project".
  org/apache/commons/lang/StringEscapeUtils

**pom.xml**
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>jp.example.daitec</groupId>
  <artifactId>checkstyle-config</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
		<java-version>1.8</java-version>
		<maven.compiler.target>${java-version}</maven.compiler.target>
		<maven.compiler.source>${java-version}</maven.compiler.source>

		<!-- checkstyle -->
		<checkstyle.configuration.location>${basedir}/.prefs/checkstyle.xml</checkstyle.configuration.location>
		<checkstyle.suppressionfilter.location>${basedir}/.prefs/suppresstionfilters.xml</checkstyle.suppressionfilter.location>
  </properties>

  <build>
  	<plugins>
		<!-- checkstyle -->
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-checkstyle-plugin</artifactId>
			<version>2.10</version>
			<configuration>
				<propertyExpansion>hoge</propertyExpansion>
			</configuration>
			<executions>
				<execution>
					<phase>compile</phase>
					<goals><goal>checkstyle</goal></goals>
				</execution>
			</executions>
		</plugin>
  	</plugins>
  </build>
</project>
```

**Comment by dairylea** [comment] 2015-09-13 12:16
I am getting this error too! Tried fresh Spring STS and Eclipse workspaces and installs (Mars).

java.lang.NoClassDefFoundError: org/apache/commons/lang/StringEscapeUtils
	at com.basistech.m2e.code.quality.checkstyle.MavenPluginConfigurationTranslator.updatePropertiesWithPropertyExpansion(MavenPluginConfigurationTranslator.java:632)
	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.buildCheckstyleConfiguration(EclipseCheckstyleProjectConfigurator.java:153)
	at com.basistech.m2e.code.quality.checkstyle.EclipseCheckstyleProjectConfigurator.handleProjectConfigurationChange(EclipseCheckstyleProjectConfigurator.java:106)
	at com.basistech.m2e.code.quality.shared.AbstractMavenPluginProjectConfigurator.mavenProjectChanged(AbstractMavenPluginProjectConfigurator.java:127)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged(ProjectConfigurationManager.java:1000)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.notifyProjectChangeListeners(ProjectRegistryManager.java:783)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.applyMutableProjectRegistry(ProjectRegistryManager.java:919)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:299)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:398)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:345)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:342)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringEscapeUtils cannot be found by com.basistech.m2e.code.quality.checkstyle_1.0.0.201503101518
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more

**Comment by marnix** [comment] 2015-09-17 12:32
A colleague has the same problem, using Luna, not STS, with 6.9.0, whiile I don't have this problem with Luna, not STS, with 6.5.0.

We have not found a workaround yet.

Let me know if there is more information we could provide to help you out.  Thanks!

**Comment by ArloL** [comment] 2015-09-23 06:39
Thanks for wriiting the issue. Since we at work stopped using the plugin for performance reasons I can't really motivate myself to really check these. I will continue merging PRs that look reasonable and release them but I won't be fixing any issues myself - especially as writing code for Eclipse is not really intuitive.

**Comment by iheinrich** [comment] 2015-09-24 11:21
PR #76 fixed this issue for me.

**Comment by dairylea** [comment] 2015-09-24 11:39
I have cloned and built locally, how do I install it?

**Comment by iheinrich** [comment] 2015-09-25 12:45
My build was done by launching Maven from the command line. After the build I added a "local" software site to Eclipse by selecting the folder "m2e-code-quality/com.basistech.m2e.code.quality.site/target/site" from file system.
There may be other options available if you import m2e-code-quality as Plugin Projects into Eclipse and build them there. But I am not familiar with Eclipse plugin development ...

**Comment by dairylea** [comment] 2015-09-25 12:56
Cheers, that did it for me!

**Comment by marnix** [comment] 2015-09-26 08:33
Just to confirm: does that mean that Checkstyle configuration plugin for M2Eclipse 1.0.0.201503101518 cannot be installed when m2e 1.7.x is installed, but it can be installed when m2e 1.6.x is installed?

If I misunderstood, please clarify.  Thanks!

**Comment by RocusHalbasch** [comment] 2015-09-27 21:40
That is correct PR #76 added support for m2e 1.7.x, and "Checkstyle configuration plugin for M2Eclipse 1.0.0.201503101518" was built before PR #76 was merged. I should have checked the issues to see if there were any outstanding issues it fixed and let you guys know. Sorry.

**Comment by ArloL** [comment] 2016-02-07 16:36
Sorry about the delay. I've just pushed a new release. Please let me know if it was fixed or whether the issue still exists!

**Comment by iheinrich** [comment] 2016-02-15 11:40
Installing 1.0.0.201602071612 into Mars.1 (4.5.1) fixed this bug for me. Thanks!

**Comment by ArloL** [comment] 2016-02-15 14:04
Thanks for the feedback, @iheinrich. I will close this issue then.

**Closed by ArloL** 2016-02-15 14:04 UTC
