### ISSUE TITLE
Not seeing Checkstyle errors at compile time

### ISSUE THREAD

**Issue by tad9ab** [m2e-code-quality/m2e-code-quality#78] opened 2015-10-01 13:51 UTC
After I've installed the Checkstyle connector, is there any other configuration I need to do to have the checkstyle plugin run whenever I make a code change (and my code auto-compiles)?

I have known checkstyle issues in my code, but I don't see them marked in
Eclipse after I compile that code.  Any help would be appreciated.

I'm using 1.0.0.201503101518 and am on Kepler SR2 (with M2E 1.5.2).  Also note, when I run "mvn install", the build fails due to the checkstyle errors in the code.  Let me know if there's anything else I can provide.

Thanks

**Comment by ArloL** [comment] 2016-02-08 19:07
Hi @tad9ab, can you look at the configuration of the /test-projects directory and see whether there are any significant differences? Otherwise could you maybe create a PR with a project that demonstrates your behavior? Then I can look into your problem!

**Comment by tad9ab** [comment] 2016-02-09 16:58
Thanks for the reply.  I thought I might state a few things and ask a question or two until I get time to upload a test project.

The project I'm currently working on pulls in its CS configuration via a (grand)parent pom, and the path is contributed by a dependent jar.  I noticed that your configuration is pulled from a "config" path, that doesn't appear to be in your project somewhere.  Perhaps those resources are contributed by the checkstyle plugin itself?

So, do you think it should still work if the config file is contributed by a jar that is listed as a dependency for the maven checkstyle plugin execution?  And are there any logs that are written so I can check to see if it's failing to load the config, or anything else it might be complaining about?  Here's the checkstyle config snippet.  Again, this is from a parent pom of the project in question.

`        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-checkstyle-plugin</artifactId>
          <version>2.17</version>
          <executions>
            <execution>
              <id>default-check</id>
              <phase>validate</phase>
              <configuration>
                <configLocation>build/checkstyle.xml</configLocation>
                <suppressionsLocation>build/checkstyle-suppressions.xml</suppressionsLocation>
                <suppressionsFileExpression>checkstyle.suppressions.file</suppressionsFileExpression>
                <encoding>UTF-8</encoding>
                <consoleOutput>true</consoleOutput>
                <failsOnError>true</failsOnError>
                <includeTestSourceDirectory>true</includeTestSourceDirectory>
              </configuration>
              <goals>
                <goal>check</goal>
              </goals>
            </execution>
          </executions>
          <dependencies>
            <dependency>
              <groupId>com.puppycrawl.tools</groupId>
              <artifactId>checkstyle</artifactId>
              <version>6.14.1</version>
            </dependency>
            <dependency>
              <groupId>com.mycompany.checkstyle</groupId>
              <artifactId>mycompany-maven-checkstyle</artifactId>
              <version>1.7</version>
            </dependency>
            <dependency>
              <groupId>com.mycompany.build</groupId>
              <artifactId>mycompany-build-tools</artifactId>
              <version>1.17</version>
            </dependency>
          </dependencies>
        </plugin>`

The dependency listed last is the one that contributes the config resource.

Hopefully that helps a bit, I will see what I can do about getting you a dummy project that exhibits the same behavior.

Thanks!

**Comment by ArloL** [comment] 2016-02-09 17:02
I edited your comment for readability of the code.

Look at the new failing-checkstyle-example project that I just committed. It uses a jar file too with configuration in the parent. The jar has to be available in your maven repository though. It won't pull it from the workspace. Does that help you?

**Comment by tad9ab** [comment] 2016-02-09 17:24
OK, sorry for the dumb question(s), but I'm assuming that "failing-checkstyle-example" is configured to give CS errors during compilation, right?  I didn't see any source code in the core or the persistence projects, so maybe I'm not understanding entirely.  I pulled it down, added a new class with a System.out.println() in the constructor, and expected to see an error (or a warning), but I'm not seeing anything.  So it's either not supposed to work as I'm expecting, or perhaps it *is* supposed to work, and is indicative of my workspace/Eclipse install being hosed?

**Comment by c4n70r** [comment] 2016-02-09 17:29
the checkstyle configuration just contains a few checks (pmd as well), it was meant to check if the eclipse-cs configuration would be done, not to really test code. I'm sorry. 
You may fill the checkstyle.xml with some more "realistic" content if you want to see messages.

**Comment by ArloL** [comment] 2016-02-09 19:02
Look at checkstyle-5. It should give you an idea!

**Comment by tad9ab** [comment] 2016-02-09 20:11
I pulled down checkstyle-5, and built both of the projects (via the command line).  I expected the build to fail for the checkstyle-5-project (due to the what appears to be the disallowing of System.out.print), but it didn't even fail from the command line.  I apologize if I'm missing something super obvious here, but I feel like I am.

Is the expectation that this project will fail when it is built via maven?  Just to let you know, I've updated my code-quality plugin via the update site earlier today (looks like a build from a day or two ago).

**Comment by ArloL** [comment] 2016-02-09 20:55
It doesn't fail since it has a suppression on directories with generated in them. If you want it to fail change https://github.com/m2e-code-quality/m2e-code-quality/blob/develop/test-projects/checkstyle-5/project-using-checkstyle-config/pom.xml#L34 to checkstyle-suppressions2.xml

**Comment by tad9ab** [comment] 2016-02-09 22:06
OK, sweet, I got it to throw warnings for System.out.print!  Looks like it must be a problem on my end somewhere.  I'll keep digging an post back here if I have any more questions/solutions.

Thanks!

**Comment by tad9ab** [comment] 2016-02-09 22:30
When I move the <build> block out of the current project, and have it contributed by the parent (it's in the "effective pom"), it no longer works.  Again, the contribution by the parent is the same as the snippet I pasted above.

If I can get some time, I will try to create a simple parent that has the build section and see if I can't get that to work.

Again, the child project has the build section contributed by a parent pom, which gets the cs config xml from a dependency, and suppressions from another dependecy.

Thanks for all of your help.

**Comment by ArloL** [comment] 2016-02-10 18:01
If you can create a PR with a project that reproduces any problems I'll definitely have a look at it.

**Comment by ArloL** [comment] 2016-02-10 21:55
Please checkout /test-project/checkstyle-6 for a working parent-pom configuration.

![screen shot 2016-02-10 at 22 54 32](https://cloud.githubusercontent.com/assets/195367/12963142/425e2f8e-d049-11e5-985d-2877d9f0ac94.png)

**Comment by tad9ab** [comment] 2016-02-10 23:40
OK, I'm just really confused at this point.  I thought I had it working, but not there's nothing I can do to get it to come back.  I'm wondering if I was just pointing at some config via the eclipse CS plugin.  Whenever it "worked", I would see a .checkstyle file generated.  I wasn't sure if that was your plugin, or the code quality plugin.  Should I expect to see that, or no?  Should I have that plugin installed?  If so, any settings I need to set for it?  Now that the .checkstyle file isn't being generated anymore, it's back to not working (or maybe it never was, but at least I was getting warnings).  I honestly don't know what I changed to stopped that file from generating.

When I pull in your checkstyle-6 project (import via existing maven projects), I see no errors.  Eclipse gives me the java, maven and checkstyle natures in the .project (if that's relevant).  Anything else I should be looking for?  I see no errors/warnings/etc.  Running it from command line does fail.

I feel like I'm missing something super obvious/silly at this point.

**Comment by ArloL** [comment] 2016-02-11 08:06
Don't worry. m2e-connectors are not really the best thing in the world but there is no alternative. You're not the only experiencing weird behavior . Which makes it very important to create reproducible situations.

The .checkstyle file you see is the checkstyle configuration of the eclipse-cs (Eclipse Checkstyle Plugin) plugin. That would exist if you create a normal Java Project and configure Checkstyle manually via Project -> Properties -> Checkstyle.

What you're trying to achieve is a bridge from the maven configuration of the maven-checkstyle-plugin to be automatically converted to eclipse-cs settings. Therefore you will always see a .checkstyle file if the configuration conversion worked.

> your plugin, or the code quality plugin

I'm not exactly sure what you mean here. If you mean code quality plugin == eclipse-cs and my plugin == m2e-code-quality-checkstyle then m2e-code-quality-checkstyle pumps the configs into eclipse-cs which writes the file.

Not sure whether that should have an influence. Did you `mvn install` the updated checkstyle-config?

**Comment by tad9ab** [comment] 2016-02-11 14:48
"your plugin, or the code quality plugin"
Whoops, that was a mistake.  I meant eclipse-cs or code-quality, my fault.  But from what you're saying, it sounds like what I had expected, but wasn't sure.

I'm going to try a bit more today, testing with different checkstyle configs, and see if that's where the difference lies.  Will update here with what I find.  Thanks for being so patient!

**Comment by ArloL** [comment] 2016-02-11 16:19
No worries. If you test with different configurations please make sure to always that the test is reproducible. Meaning always delete all the eclipse configuration when trying something different with e.g. `git clean -fdx`. This will delete *all* untracked and ignored (!) files. I've had success with that.

**Comment by tad9ab** [comment] 2016-02-12 15:58
OK, I've had a bit more time to take a look, and I think I might have found something.  Or I'm just going crazy at this point.

It looks like our <build> section is slightly different in that the maven checkstyle plugin is under
<build><pluginManagement><plugins>...</build>

If i wrap checkstyle6-project with pluginManagement tags, it stops working (defaults to eclipse-cs).  If I remove those tags, it starts working again.

There might be one more problem that is completely different, but I'll investigate that a bit more before I elaborate.

Here's the snippet that fails...
```
      <build>
       <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.17</version>
                <dependencies>
                    <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>checkstyle-5-config</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <failsOnError>true</failsOnError>
                    <configLocation>config/checkstyle.xml</configLocation>
                    <suppressionsLocation>config/checkstyle-suppressions.xml</suppressionsLocation>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>checkstyle</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
       </pluginManagement>
    </build>
```

**Comment by ArloL** [comment] 2016-02-12 16:22
Does `mvn install` fail with that setup? My guess is no. And the answer is because the `maven-checkstyle-plugin` is not part of the build. What you add to `build/pluginManagement/plugins` configures defaults for what you add to `/build/plugins`. But it has to be part of `/build/plugins` like this

```
<build>
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.17</version>
                <dependencies>
                    <dependency>
                        <groupId>${project.groupId}</groupId>
                        <artifactId>checkstyle-5-config</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <failsOnError>true</failsOnError>
                    <configLocation>config/checkstyle.xml</configLocation>
                    <suppressionsLocation>config/checkstyle-suppressions.xml</suppressionsLocation>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>checkstyle</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </pluginManagement>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-checkstyle-plugin</artifactId>
        </plugin>
    </plugins>
</build>
```

**Comment by tad9ab** [comment] 2016-02-12 16:30
Well crap, it is there from the parent, but wasn't in my test.  Let me keep trying to dissect the differences.  Sorry about that!

**Comment by ArloL** [comment] 2016-02-13 11:36
The m2e lifecycle-mapping is a nice trick by the m2e guys. What it tells m2e is to either ignore or execute the maven plugin. In your gist we see this for the maven-checkstyle-plugin:

```
<pluginExecution>
    <pluginExecutionFilter>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <versionRange>[2.15,)</versionRange>
        <goals>
            <goal>check</goal>
        </goals>
    </pluginExecutionFilter>
    <action>
        <ignore />
    </action>
</pluginExecution>
```

The interesting part is `<action><ignore /></action>`. If you override this in your project with `<action><execute /></action>`. It should work.

In the effective pom (checkout the tab in the eclipse pom editor) of the project where you want the m2e-code-quality-checkstyle to do the conversion it should look like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<plugin>
    <groupId>org.eclipse.m2e</groupId>
    <artifactId>lifecycle-mapping</artifactId>
    <version>1.0.0</version>
    <configuration>
        <lifecycleMappingMetadata>
            <pluginExecutions>
                <pluginExecution>
                    <pluginExecutionFilter>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-checkstyle-plugin</artifactId>
                        <versionRange>[2.15,)</versionRange>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </pluginExecutionFilter>
                    <action>
                        <execute />
                    </action>
                </pluginExecution>
            </pluginExecutions>
        </lifecycleMappingMetadata>
    </configuration>
</plugin>
```

See https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html#execute-plugin-goal for details.

**Comment by tad9ab** [comment] 2016-02-18 16:17
I apologize for the delay, I haven't had a moment to circle back on this until this morning.

I reduced the build block to only contain the maven-checkstyle-plugin and the m2e plugin, which now looks like this...
```
        <plugin>
          <groupId>org.eclipse.m2e</groupId>
          <artifactId>lifecycle-mapping</artifactId>
          <version>1.0.0</version>
          <configuration>
            <lifecycleMappingMetadata>
              <pluginExecutions>
                <pluginExecution>
                  <pluginExecutionFilter>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <versionRange>[2.15,)</versionRange>
                    <goals>
                      <goal>check</goal>
                    </goals>
                  </pluginExecutionFilter>
                  <action>
                    <execute />
                  </action>
                </pluginExecution>
              </pluginExecutions>
            </lifecycleMappingMetadata>
          </configuration>
        </plugin>
```

If I remove the pluginExecution block, it works again, so maybe just the fact that it's there?  I also tried to "remove" the execution block in the child by doing something like
```
    <build>
      <plugins>
        <plugin>
          <groupId>org.eclipse.m2e</groupId>
          <artifactId>lifecycle-mapping</artifactId>
          <configuration combine.self="override">
          </configuration>
        </plugin>
      </plugins>
    </build>
```
but that doesn't seem to work either.  Does something still look wrong about my snippet?  Comparing to yours, they look the same, but I wouldn't be surprised if I've overlooked a detail.

Thanks again, and sorry for the long delay!

**Comment by ArloL** [comment] 2016-02-19 17:53
I checked the Lifecycle Mapping and saw that using `<execute />` will not use the connector. The column to check is `Source` and it was `pom`. But it has to be `extension`. So I checked and found that in order to override the `<ignore />` or `<execute />` of a parent pom you have to use the following configuration

```
<pluginExecution>
    <pluginExecutionFilter>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <versionRange>[2.17,)</versionRange>
        <goals>
            <goal>checkstyle</goal>
        </goals>
    </pluginExecutionFilter>
    <action>
        <configurator>
            <id>com.basistech.m2e.code.quality.checkstyleConfigurator</id>
        </configurator>
    </action>
</pluginExecution>
```

**Comment by tad9ab** [comment] 2016-02-19 23:33
Awesome, that did it!  One other thing that's left.  It's failing when trying to load a custom class from the checkstyle config, but I'll try to dig in and get more info before I post anything.  Hopefully I'll have some time next week to look.

Thanks again!

**Comment by tad9ab** [comment] 2016-02-22 19:48
OK, this might just be a Checkstyle plugin error, so not sure if this is something you can help with...

We use a TreeWalker in our checkstyle config.  One of the modules under the TreeWalker module is a custom class provided by one of our jars (a dependency on the maven checkstyle plugin).  When the code quality and/or CS plugin runs, I get the following error:

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Unable to instantiate 'com.company.checkstyle.LombokCheck' class
```
Again, to clarify, this runs fine when on the command line.  If this needs to be a separate issue, let me know.

**Comment by ArloL** [comment] 2016-02-24 18:02
I can reproduce your problem with a custom check. The problem is that the custom class is not on Eclipse's classpath. Therefore eclipse-cs cannot instantiate the class. There are some solutions described here:

https://sourceforge.net/p/eclipse-cs/discussion/274377/thread/cde2811d/
http://eclipse-cs.sourceforge.net/#!/extensions
http://eclipse-cs.sourceforge.net/#!/custom-checks

Hopefully you can work with that. Do you have any other problems using the connector?

**Comment by tad9ab** [comment] 2016-02-24 19:26
I *think* this is the last issue.  So there's no way that code quality can make resources that are available to itself, also available to the CS plugin?  For example, the jars that contain the cs config are not loaded via Eclipse's classpath, yet it finds those.  I'm obviously not familiar with the "handoff" it does with the CS plugin.  Perhaps it simply retrieves the config files to provide to the CS plugin?  The obvious problem with the proposed solution is when the custom check code changes, we now have to create a new plugin/reference a new jar.  I was hoping for this to be as hands off as possible.

Thanks again for all of your help!

**Comment by ArloL** [comment] 2016-02-25 10:23
The checkstyle configuration is loaded straight from the JAR. You can see that in the project properties:

![screen shot 2016-02-25 at 11 18 41](https://cloud.githubusercontent.com/assets/195367/13316703/9f01dcc2-dbb1-11e5-8357-00bd417a71b3.png)

Sadly there doesn't seem to be a similar way to do that for custom checks.

m2e connectors are just configuration converters. They read the maven configuration and apply that to an eclipse plugin. So if eclipse-cs can't do it then m2e-code-quality can't do anything about it.

Your welcome! Hope you'll find a way to make it work. I'll close the issue then. Please just open a new one or use the mailing list if you have another question.

**Closed by ArloL** 2016-02-25 10:23 UTC
