### ISSUE TITLE
Not compatible with Photon?

### ISSUE THREAD

**Issue by vguna** [m2e-code-quality/m2e-code-quality#120] opened 2018-06-28 10:30 UTC
Just trying the new Eclipse Photon version.
When I try to install the m2e connector for checkstyle it fails on pre-condition checks:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Checkstyle configuration plugin for M2Eclipse 1.0.0.201705301746 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201705301746)
  Missing requirement: M2Eclipse Project Configurator for Eclipse Checkstyle 1.0.0.201705301746 (com.basistech.m2e.code.quality.checkstyle 1.0.0.201705301746) requires 'osgi.bundle; org.eclipse.m2e.jdt [1.0.0,1.9.0)' but it could not be found
  Cannot satisfy dependency:
    From: Checkstyle configuration plugin for M2Eclipse 1.0.0.201705301746 (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.0.0.201705301746)
    To: org.eclipse.equinox.p2.iu; com.basistech.m2e.code.quality.checkstyle [1.0.0.201705301746,1.0.0.201705301746]
```
Is this a known issue?

**Comment by balazs-zsoldos** [comment] 2018-06-29 08:56
+1

**Comment by antoine-morvan** [comment] 2018-06-29 09:10
Hi, 

Jesse Ghallager made an update with tweaks for Photon compatibility (see this fork https://github.com/jesse-gallagher/m2e-code-quality/commit/7ccac314d0c972656d567ba5287013c01ee32cef).

I made a second fork where I temporarily set up a P2 repo with binaries built using the tweaks, at this URL:
http://preesm.github.io/m2e-code-quality/site/latest/

I'll use this while waiting for a proper update.

**Comment by victornoel** [comment] 2018-07-07 13:42
For the record, a PR is waiting to be merged for this: #121

**Comment by jodastephen** [comment] 2018-07-09 10:21
The fork of this plugin from [GEBIT](https://github.com/GEBIT/m2e-code-quality/tree/develop) also works on Photon. I've uploaded a binary zip to my [eclipse-setup](https://github.com/jodastephen/eclipse-setup) repo.

**Comment by jmini** [comment] 2018-07-12 04:21
The version on this update site is not working for me:
```
http://preesm.github.io/m2e-code-quality/site/latest/
```

For the GEBIT fork, is there a P2 Update Site somewhere?

**Comment by victornoel** [comment] 2018-07-12 06:18
@ArloL can something be done about that? :)

**Comment by jmini** [comment] 2018-07-12 16:42
The Update Site (`preesm` user) works. I was too quick during my test this morning. I have updated my comment.

**Comment by rexhoffman** [comment] 2018-07-19 00:20
I have checkstyle and findbugs working, but not pmd (I keep my pmd config in a jar next to the checkstyle config, as an extra dependency attached to pmd/checkstyle plugin in maven config.  In the past I had to pin 4.15 of the pmd eclipse plugin to have it pick up a pmd config file from a jar, now that doesn't seem to be an option.   Willing to fix this if there is a place this code will be maintained -- but it looks like a couple good prs are sitting (spotbugs work and others).   Does someone want to spin up a new organization to run this project.   I'm willing to lend a hand.

**Comment by ctron** [comment] 2018-07-30 16:08
I can confirm that the update site is working:

> http://preesm.github.io/m2e-code-quality/site/latest/

Thanks for sharing this!

**Comment by vorburger** [comment] 2018-09-19 11:20
@vguna @balazs-zsoldos @antoine-morvan @jodastephen @victornoel @jmini @rexhoffman @ctron could you please re-test with our brand new update site at https://m2e-code-quality.github.io/m2e-code-quality-p2-site/ (see #123 for #124 for background), and shout by further commenting here in this issue with more details from your error log if it's still NOK for you? The problem shown above re. org.eclipse.m2e.jdt [1.0.0,1.9.0) should normally now be fixed (by #115).

**Comment by antoine-morvan** [comment] 2018-09-19 11:55
Seems good: https://travis-ci.org/preesm/graphiti/builds/430499654 :+1:

**Comment by jodastephen** [comment] 2018-09-19 13:03
I'm using the new update side in Eclipse now for checkstyle. It loads fine (which is what this issue is about). I suspect I also need #117 fixed for a complete solution. Thanks!

**Closed** 2018-09-19 13:34 UTC

**Comment by antoine-morvan** [comment] 2018-09-19 14:02
Activated redirection from previous temporary repo : https://github.com/preesm/m2e-code-quality/commit/2a3742207f799bfb20e2897e217ace5ee2be8894
