### ISSUE TITLE
Eclipse 4.19: net.sf.eclipsecs.core 5.2.0 but it could not be found

### ISSUE THREAD

**Issue by Anymous526** [m2e-code-quality/m2e-code-quality#250] opened 2021-06-08 06:13 UTC
Cannot complete the install because one or more required items could not be found.
  Software being installed: Checkstyle configuration plugin for M2Eclipse 1.1.4.201906210825-r (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.1.4.201906210825-r)
  Missing requirement: Checkstyle configuration plugin for M2Eclipse 1.1.4.201906210825-r (com.basistech.m2e.code.quality.checkstyle.feature.feature.group 1.1.4.201906210825-r) requires 'org.eclipse.equinox.p2.iu; net.sf.eclipsecs.core 5.2.0' but it could not be found

**Comment by adangel** [comment] 2021-09-17 10:05
Hi @Anymous526 ,
this might have been caused by the outdated update site url for checkstyle (see #251, #255).

Could you try to install the latest snapshot from https://m2e-code-quality.github.io/m2e-code-quality-p2-site/snapshot/ ?
Maybe that's then fixed now...

**Comment by adangel** [comment] 2021-09-17 18:39
I can confirm, that this is fixed now - will be shipped with the next release.

**Closed by adangel** 2021-09-17 18:39 UTC
